package Acme::CPANLists::Import::PERLANCAR::GetoptModules;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [https://perlancar.wordpress.com/2016/12/02/getopt-modules-02-getoptstd/] (retrieved on 2016-12-26). Visit the URL for the full contents.",entries=>[{module=>"Getopt::Long"},{module=>"Getopt::Long::Complete"},{module=>"Getopt::Long::Descriptive"},{module=>"Getopt::Std"},{module=>"Getopt::Compact"},{module=>"Docopt"},{module=>"Getopt::Euclid"},{module=>"Opt::Imistic"},{module=>"overload"},{module=>"Getopt::Lucid"},{module=>"Getopt::Std::Strict"},{module=>"Getopt::Declare"},{module=>"Getopt::Long::More"},{module=>"Getopt::Simple"},{module=>"Getopt::Tiny"},{module=>"App::Options"},{module=>"Getopt::Auto"},{module=>"MooX::Options"},{module=>"MooseX::Getopt"},{module=>"Smart::Options"},{module=>"Getopt::ArgvFile"},{module=>"Perinci::CmdLine"},{module=>"App::Cmd"},{module=>"Config::Any"},{module=>"DateTime"},{module=>"Moose"},{module=>"MooseX::App::Cmd"},{module=>"MooseX::ConfigFromFile"},{module=>"MooseX::Getopt::Strict"},{module=>"MooseX::SimpleConfig"},{module=>"MooX::ConfigFromFile"},{module=>"Getopt::Attribute"},{module=>"Getopt::Awesome"},{module=>"Getopt::Modular"},{module=>"Dist::Zilla"},{module=>"App::Spec"},{module=>"Getopt::Long::Subcommand"},{module=>"Smart::Options::Declare"},{module=>"opts"},{module=>"Getopt::ArgParse"},{module=>"Moo"},{module=>"Getopt::Kingpin"},{module=>"Complete::Util"},{module=>"Shell::Completer"},{module=>"Getopt::Alt"},{module=>"Getopt::Chain"},{module=>"Getopt::Fancy"},{module=>"Getopt::Flex"},{module=>"Getopt::Helpful"},{module=>"Getopt::Long::EvenLess"},{module=>"Getopt::Long::Less"},{module=>"Getopt::Panjang"},{module=>"Perinci::CmdLine::Lite"}],summary=>"Modules mentioned in PERLANCAR's mini-article series on Getopt modules (2016)"});

1;
# ABSTRACT: Modules mentioned in PERLANCAR's mini-article series on Getopt modules (2016)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://perlancar.wordpress.com/2016/12/02/getopt-modules-02-getoptstd/> (retrieved on 2016-12-26). Visit the URL for the full contents.

