#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

my %urls = (
    "01" => "https://perlancar.wordpress.com/2016/12/01/getopt-modules-01-getoptlong/",
    "02" => "https://perlancar.wordpress.com/2016/12/02/getopt-modules-02-getoptstd/",
    "03" => "https://perlancar.wordpress.com/2016/12/03/getopt-modules-03-getoptlongdescriptive/",
    "04" => "https://perlancar.wordpress.com/2016/12/04/getopt-modules-04-getoptcompact/",
    "05" => "https://perlancar.wordpress.com/2016/12/06/getopt-modules-05-getoptvalid/",
    "05" => "https://perlancar.wordpress.com/2016/12/06/getopt-modules-99-optimistic/",
    "07" => "https://perlancar.wordpress.com/2016/12/07/getopt-modules-07-getoptstdstrict/",
    "08" => "https://perlancar.wordpress.com/2016/12/07/getopt-modules-08-getopttiny/",
    "09" => "https://perlancar.wordpress.com/2016/12/09/getopt-modules-09-getoptdeclare-getopteuclid-docopt/",
    "10" => "https://perlancar.wordpress.com/2016/12/10/getopt-modules-10-getoptauto/",
    "11" => "https://perlancar.wordpress.com/2016/12/12/getopt-modules-11-getoptlucid/",
    "12" => "https://perlancar.wordpress.com/2016/12/12/getopt-modules-12-getoptargvfile/",
    "13" => "https://perlancar.wordpress.com/2016/12/13/getopt-modules-13-appoptions/",
    "14" => "https://perlancar.wordpress.com/2016/12/14/getopt-modules-14-moosexgetopt/",
    "15" => "https://perlancar.wordpress.com/2016/12/15/getopt-modules-15-mooxoptions/",
    "16" => "https://perlancar.wordpress.com/2016/12/16/getopt-modules-16-getoptattribute/",
    "17" => "https://perlancar.wordpress.com/2016/12/19/getopt-modules-17-getoptmodular/",
    "18" => "https://perlancar.wordpress.com/2016/12/19/getopt-modules-18-appcmd/",
    "19" => "https://perlancar.wordpress.com/2016/12/19/getopt-modules-19-appspec/",
    "20" => "https://perlancar.wordpress.com/2016/12/20/getopt-modules-20-smartoptions/",
    "21" => "https://perlancar.wordpress.com/2016/12/21/getopt-modules-21-getoptargparse/",
    "22" => "https://perlancar.wordpress.com/2016/12/22/getopt-modules-22-getoptargparse/",
    "23" => "https://perlancar.wordpress.com/2016/12/23/getopt-modules-23-getoptcomplete/",
    "24" => "https://perlancar.wordpress.com/2016/12/24/getopt-modules-epilogue/",
);

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => 'GetoptModules',
                url => "https://perlancar.wordpress.com/2016/12/02/getopt-modules-02-getoptstd/",
                extract_urls => [map { $urls{$_} } "01".."24"],
                summary => "Modules mentioned in PERLANCAR's mini-article series on Getopt modules (2016)",
            },
        ],
        namespace => 'Acme::CPANLists::Import::PERLANCAR',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
